Per bug report #79 - error message encountered when running recent autoconf (2.63) on autoconf.ac.
-----------------
configure.ac:89: error: AC_SUBST: `2.0.1' is not a valid shell variable name
configure.ac:89: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
error: Bad exit status from /var/tmp/rpm-tmp.CLmZ2P (%build)
-----------------

Commented out AC_SUBST(SLONREL_VERSION), which is the nexus of the problem.

SLONREL_VERSION isn't used in any of the .in files, so this seems a safe
change.